#!/bin/bash
set -euo pipefail

if git diff --cached --quiet; then
    echo "No staged changes."
    echo "Stage files manually, then rerun ./check-push."
    exit 1
fi

./check-commit
git push --follow-tags

echo
echo "$(tput setab 2)$(tput setaf 7)*** GIT-PUSH SUCCESS ***$(tput sgr0)"
echo
